# Generated by Django 2.0.4 on 2018-04-20 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Localnegocio',
            fields=[
                ('idNegocio', models.IntegerField(primary_key=True, serialize=False)),
                ('latitud', models.FloatField()),
                ('longitud', models.FloatField()),
                ('descripcion', models.TextField()),
            ],
            options={
                'ordering': ('idNegocio',),
            },
        ),
    ]
