# Generated by Django 2.0.4 on 2018-04-20 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('localnegocio', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='localnegocio',
            options={'managed': False},
        ),
    ]
