# Generated by Django 2.0.4 on 2018-04-22 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('localnegocio', '0002_auto_20180420_1045'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='localnegocio',
            options={'managed': True},
        ),
    ]
