# Generated by Django 2.0.4 on 2018-05-21 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('localnegocio', '0003_auto_20180422_1656'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='localnegocio',
            options={'managed': False},
        ),
    ]
