# Generated by Django 2.0.4 on 2018-05-22 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('localnegocio', '0004_auto_20180521_1101'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='localnegocio',
            table='localnegocio',
        ),
    ]
