# Generated by Django 2.0.4 on 2018-06-05 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localnegocio', '0005_auto_20180522_1045'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admnegocio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'admnegocio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'cliente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Dia',
            fields=[
                ('id', models.CharField(max_length=1, primary_key=True, serialize=False)),
                ('nomdia', models.CharField(max_length=2)),
            ],
            options={
                'db_table': 'dia',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Disponibilidadprofesional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horainicio', models.CharField(max_length=2)),
                ('horafin', models.CharField(max_length=2)),
            ],
            options={
                'db_table': 'disponibilidadprofesional',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Migrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('migration', models.CharField(max_length=191)),
                ('batch', models.IntegerField()),
            ],
            options={
                'db_table': 'migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PasswordResets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=191)),
                ('token', models.CharField(max_length=191)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'password_resets',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pedidoproducto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
            ],
            options={
                'db_table': 'pedidoproducto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Prodnegocios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=3)),
                ('stock', models.IntegerField()),
            ],
            options={
                'db_table': 'prodnegocios',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Productolocal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomproducto', models.CharField(max_length=40)),
                ('descripcion', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'productolocal',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Profesionales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomprofesional', models.CharField(max_length=45)),
                ('correoprofesional', models.CharField(max_length=45)),
                ('telefonoprofesional', models.CharField(max_length=9)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'profesionales',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomservico', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'servicio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Serviciolocal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
            options={
                'db_table': 'serviciolocal',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tipolocalproducto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'tipolocalproducto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tiponegocio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'tiponegocio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tipoproducto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomtipo', models.CharField(max_length=191)),
            ],
            options={
                'db_table': 'tipoproducto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('lastname', models.CharField(max_length=45)),
                ('dni', models.CharField(max_length=9, unique=True)),
                ('username', models.CharField(max_length=45)),
                ('password', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=45, unique=True)),
                ('remember_token', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
    ]
